name: "test"
on:
- push
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Remove apt repos that are known to break from time to time
    # See https://github.com/actions/virtual-environments/issues/323
    # https://github.community/t/file-has-unexpected-size-89974-89668-mirror-sync-in-progress/17450/2
    - name: Remove broken apt repos [Ubuntu]
      if: matrix.os == 'ubuntu-latest'
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    - name: Add dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y yosys inkscape nodejs npm
    - name: Test netlistsvg
      run: |
        node --version
        npm --version
        npm install
        npm test
        npm run build-demo
        cd examples; make build.all; cd ..
